### ISSUE TITLE
The SC Alerts and Record pages, as well as the list generated in

### ISSUE THREAD

**Issue by TNP-Bug-Reporter** [The-North-Pacific/s13_TNP#33] opened 2015-09-09 15:05 UTC
http://forum.thenorthpacific.org/pages/sc-alerts/

The problem recurs when on clicks to open each of the respective SC pages. All of them are dependent on data from the NS web site feeds.

This is the second time this problem has arisen in the past week.

See above

~[Grosseschnauzer](http://forum.thenorthpacific.org/profile/197293)

**Comment by Eluvatar** [comment] 2015-10-15 09:23
Duplicate of #31

**Closed by Eluvatar** 2015-10-15 09:23 UTC
Labels: bug
